name: project

# Add other packages you are using here
dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Werror                   # warnings are errors
- -Wincomplete-patterns     # cover all cases!
- -Wunused-binds            # use all your bindings
- -Wunused-matches          # use all your pattern matches!
- -Wmissing-signatures      # write all your toplevel signatures!
- -Wname-shadowing          # use different names!
- -Wincomplete-uni-patterns # warn about incomplete patterns v2

library:
  source-dirs: src

executables:
  my-ultra-cool-project:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - project
